---
- hosts: "{{ hname }}"
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  vars_files:
    - variables.yml
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      tags: update
      register: out
    - name: epel-release
      yum:
        name: epel-release
      tags: epel
    - name: Install a list of packages with a list variable
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - htop
          - telnet-server
          - telnet
          - wget
          - net-tools
          - git
          - python3
          - python3-pip
          - nfs-utils
          - httpie

  # Config limit parameters
    - name: soft
      shell: echo "*    soft    nofile 819200" >>/etc/security/limits.conf
    - name: hard
      shell: echo "*    hard    nofile 819200" >>/etc/security/limits.conf
    - name: touch
      shell: touch /etc/security/limits.conf
    - name: file-max
      shell: echo "fs.file-max = 200000" >>/etc/sysctl.conf
    - name: inotify.max_user_watches
      shell: echo "fs.inotify.max_user_watches = 2048576" >>/etc/sysctl.conf
    - name: inotify.max_user_instances
      shell: echo "fs.inotify.max_user_instances = 524288" >>/etc/sysctl.conf
      
  # cai dat docker
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: install git pip
      yum:
        name:
          - python3
          - python3-pip
          - git
    - name: Upgrade pip
      shell: pip3 install --upgrade pip==21.3.1
   
    - name: install docker sdk
      shell: |
        pip install docker
        pip install docker-compose

    - name: Insert data to daemon.json
      shell: |
        printf '{
           "insecure-registries": [
             "dockerhub.dttt.vn"
             ],
           "data-root":"/home/docker",
           "log-driver": "json-file",
           "log-opts": {
             "max-size": "10m",
             "max-file": "3"
           },
           "metrics-addr": "0.0.0.0:9323"
        }' > /etc/docker/daemon.json
      tags: daemon
#    - name: restart daemon
#      command: systemctl restart docker
    - name: Restart service docker, in all cases
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Cai dat docker swarm
      shell: docker swarm init
    - name: swarm update
      shell: docker swarm update --task-history-limit 3
    - name: login dockerhub.dttt.vn
      shell: docker login dockerhub.dttt.vn -u="admin" -p="Trinam@2019"
      register: ps

    - debug: var=ps.stdout_lines
    
    - name: Add port to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 2376/tcp
        - 2377/tcp
        - 4789/tcp
        - 7946/tcp
        - 2377/udp
        - 4789/udp
        - 7946/udp
        - 9001/tcp       

    - name: reload firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded
    - name: Restart service docker, in all cases
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Clone a github repository
      git:
        repo: "https://github.com/dangkhoa0797/setup.git"
        dest: /root/setup
        clone: yes
        update: yes
      tags: git    
#    - name: pull image 1
#      command: docker pull dockerhub.dttt.vn/documentserver:3.0
#      tags: im1
#    - name: pull image 2
#      shell: docker pull dockerhub.dttt.vn/etcdkeeper:latest
#    - name: pull image 3
#      shell: docker pull dockerhub.dttt.vn/imagemagick:latest
    
    # cai dat portainer

    - name: Cai dat Portaier
      shell: |
        docker stack deploy -c /root/setup/portainer-agent-stack.yml portainer

    - name: Cai dat traefik
      shell: |
        docker volume create ssl
        docker network create -d overlay traefik_main
        docker stack deploy -c /root/setup/traefik.yml traefik

    - name: Tao volume
      shell: |
        docker volume create mongo_data
        docker volume create rabbitmq_data
        docker volume create redis_data
        docker volume create rabbitmq_data
        docker volume create etcd_data
        docker volume create sqlserver_data
        
     # tao net work   
    - name: Tao network
      shell: |
        docker network create infrastructure -d overlay
    
    - name: config redis
      shell: |
        echo "user root on allkeys allchannels allcommands >VgJyAzye2YZIz3nT
        user default off" | docker config create redis.conf -

    - name: Cai dat infrastructure
      shell: |
        docker stack deploy -c /root/setup/infrastructure.yml infra

    - name: xoa file cau hinh cu
      shell: rm -rf /Scripts/telegram.sh

    - name: tao dich vu telegram
      shell: |       
        printf 'Description=Sending Alert telegram on System shutdown.
          Requires=network.target
          Before=shutdown.target reboot.target
          
          [Service]
          Type=oneshot
          RemainAfterExit=true
          ExecStart=/Scripts/telegram.sh startup
          ExecStop=/Scripts/telegram.sh shutdown
          
          [Install]
          WantedBy=multi-user.target' > /etc/systemd/system/telegram.service
      tags: telegram

    - name: tao file telegram.sh
      ansible.builtin.blockinfile:
        path: /Scripts/telegram.sh
        create: yes
        block: |
          #! /bin/sh
          ipaddr=$(hostname -I)
          if [ "$1" = startup ]
          then
              ACTION="started successfully at"
          else
              ACTION="is shutting down at"
          fi
          
          curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "-752042769", "text": "'"${ipaddr} ${ACTION}"'", "disable_notification": true}' https://api.telegram.org/bot5383352628:AAFlO9XBDATu8ZDNU9BklVyAvkgJWaI8USw/sendMessage
      tags: telegram

    - name: remove the error character
      shell: sed -i '2,11! d' /Scripts/telegram.sh
      tags: telegram
    - name: remove the error character 2
      shell: truncate -s-1 /Scripts/telegram.sh
      tags: telegram
    - name: cap quyen thuc thi telegram
      shell: chmod u+x /Scripts/telegram.sh
      tags: telegram
    
    - name: khoi dong dich vu telegram
      shell: |
        systemctl daemon-reload
        systemctl start telegram.service
        systemctl enable telegram.service
      tags: telegram


# GỬI THÔNG BÁO ĐẾN TELEGRAM NẾU PING ĐẾN FACEBOOK THẤT BẠI

    - name: tao file 
      ansible.builtin.blockinfile:
        path: /usr/local/bin/pingg.sh
        create: yes
        block: |
          #!/bin/bash
          SERVERIP="facebook.com"
          hostname=${HOSTNAME}
          
          ping -c 2 facebook.com > /dev/null 2>&1
          if [ $? -ne 0 ]
          then
              curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "-752042769", "text": "server: '${hostname}' ping google failure", "disable_notification": true}' https://api.telegram.org/bot5383352628:AAFlO9XBDATu8ZDNU9BklVyAvkgJWaI8USw/sendMessage
          fi
      tags: pingg

    - name: xóa ký tự gây lỗi
      shell: sed -i '2,10! d' /usr/local/bin/pingg.sh
      tags: pingg

    - name: cap quyen thuc thi telegram
      shell: chmod u+x /usr/local/bin/pingg.sh
      tags: pingg

    - name: tao dich vu ping
      shell: |       
        printf '[Unit]
          Description=ping google
          
          [Service]
          ExecStart=/usr/local/bin/pingg.sh' > /etc/systemd/system/pingg.service
      tags: pingg

    - name: tao timer ping
      shell: |       
        printf '[Unit]
          Description=ping "google.com" timer
          
          [Timer]
          OnBootSec=0min
          OnCalendar=*:*:0/30
          Unit=pingg.service
          
          [Install]
          WantedBy=multi-user.target' > /etc/systemd/system/pingg.timer
      tags: pingg
    
    - name: kich hoat dich vu
      shell: |
        sudo systemctl daemon-reload
        sudo systemctl start pingg.timer
        sudo systemctl enable pingg.timer

    - name: restart docker weekly At 00:00 on Sunday
      ansible.builtin.cron:
       name: "restart docker weekly"
       state: present
       minute: "0"
       hour: "0"
       day: "*"
       month: "*"
       weekday: "sun" # can be replaced sun with 0
       job: 'systemctl restart docker'
      tags: restartdocker 
    
    - name: restart redis At 00:20 every day
      ansible.builtin.cron:
       name: "restart redis every day"
       state: present
       minute: "20"
       hour: "0"
       day: "*"
       month: "*"
       weekday: "*"
       job: 'systemctl restart redis'
      tags: restartredis

    - name: Remove all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes. At 00:10 every day
      ansible.builtin.cron:
       name: "docker system prune every day"
       state: present
       minute: "10"
       hour: "0"
       day: "*"
       month: "*"
       weekday: "*"
       job: 'docker system prune -f'
      tags: prune
