---
- hosts: "{{ hname }}"
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  vars_files:
    - variables.yml
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      tags: update
      register: out
    - name: epel-release
      yum:
        name: epel-release
      tags: epel
    - name: Install a list of packages with a list variable
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - htop
          - telnet
          - wget
          - net-tools
          - git
          - nfs-utils

  # Config limit parameters
    - name: soft
      shell: echo "*    soft    nofile 819200" >>/etc/security/limits.conf
    - name: hard
      shell: echo "*    hard    nofile 819200" >>/etc/security/limits.conf
    - name: touch
      shell: touch /etc/security/limits.conf
    - name: file-max
      shell: echo "fs.file-max = 200000" >>/etc/sysctl.conf
    - name: inotify.max_user_watches
      shell: echo "fs.inotify.max_user_watches = 2048576" >>/etc/sysctl.conf
    - name: inotify.max_user_instances
      shell: echo "fs.inotify.max_user_instances = 524288" >>/etc/sysctl.conf
        
  # cai dat docker
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Insert data to daemon.json
      shell: |
        printf '{
           "insecure-registries": [
             "dockerhub.dttt.vn"
             ],
           "data-root":"/home/docker",
           "log-driver": "json-file",
           "log-opts": {
             "max-size": "10m",
             "max-file": "3"
           },
           "metrics-addr": "0.0.0.0:9323"
        }' > /etc/docker/daemon.json
      tags: daemon
    - name: restart daemon
      command: systemctl restart docker
    - name: Restart service docker, in all cases
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: join swarm
      shell: docker swarm join --token "{{ token }}" "{{ ip }}"
      tags: swarm
    
#    - name: mount volume
#      shell: |
#        yum -y install nfs-utils
#        mount -t nfs 10.0.68.73:/mnt/dockersharedfile/volumes /home/docker/volumes
