---
- hosts: "{{ hname }}"
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  tasks:
    - name: Insert data to daemon.json
      shell: |
        printf '{
           "insecure-registries": [
             "dockerhub.dttt.vn"
             ],
           "data-root":"/"{{ filedr }}"/docker",
           "log-driver": "json-file",
           "log-opts": {
             "max-size": "10m",
             "max-file": "3"
           },
           "metrics-addr": "0.0.0.0:9323"
        }' > /etc/docker/daemon.json
      tags: daemon