---
- hosts: "{{ hname }}"
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  vars_files:
    - variables.yml
  tasks:
    - name: pass
      shell: echo "Trinam@2019" >~/pass.txt
    - name: login dockerhub.dttt.vn
      shell: cat ~/pass.txt | docker login dockerhub.dttt.vn --username admin --password-stdin