---
- hosts: "{{ hname }}"
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  vars_files:
    - variables.yml
  tasks:
  # cai dat docker
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: install git pip
      yum:
        name:
          - python3
          - python3-pip
          - git
          - nfs-utils
    - name: Upgrade pip
      shell: pip3 install --upgrade pip==21.3.1
   
    - name: install docker sdk
      shell: |
        pip install docker
        pip install docker-compose

    - name: Insert data to daemon.json
      shell: |
        printf '{
           "insecure-registries": [
             "dockerhub.dttt.vn"
             ],
           "data-root":"/FILEDR/docker",
           "log-driver": "json-file",
           "log-opts": {
             "max-size": "10m",
             "max-file": "3"
           },
           "metrics-addr": "0.0.0.0:9323"
        }' > /etc/docker/daemon.json
      tags: daemon
#    - name: restart daemon
#      command: systemctl restart docker
#    - name: Restart service docker, in all cases
#      ansible.builtin.service:
#        name: docker
#        state: restarted
#    - name: mount volume
#      shell: mount -t nfs 10.0.68.73:/mnt/dockersharedfile/volumes /home/docker/volumes
    
    - name: join swarm
      shell: docker swarm join --token "{{ token }}"

    - name: Restart service docker
      ansible.builtin.service:
        name: docker
        state: restarted