---
- hosts: NAME
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  vars_files:
    - variables.yml
  tasks:
    # cai dat cac goi package
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      tags: update
    - name: epel-release
      yum:
        name: epel-release
      tags: epel
    - name: Install a list of packages with a list variable
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - htop
          - telnet
          - wget
          - net-tools
#          - cockpit
#          - nload
#          - openssh
#          - openssh-server
#          - openssh-clients
#          - openssl-libs
#          - chrony
#
#    - name: Start cockpit service
#      service:
#        name: cockpit
#        state: started
#    
#    - name: Start sshd service
#      service:
#        name: sshd
#        state: started
#    
    - name: Restart service docker
      ansible.builtin.service:
        name: docker
        state: restarted