---
- hosts: centos7.1
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes  
  tasks:
    # cai dat cac goi package

    - name: Install a list of packages with a list variable
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - htop
        - telnet
        - wget
        - curl
       - cockpit
       - net-tools
       - nload
       - openssh
       - openssh-server
       - openssh-clients
       - openssl-libs
       - chrony

    - name: Start cockpit service
      service:
        name: cockpit
        state: started
    
    - name: Start sshd service
      service:
        name: sshd
        state: started
    
    - name: Start chronyd service
      service:
        name: chronyd
        state: started