    # cai dat cac goi package
    - name: upgrade all packages
      yum: name=* state=latest

    - name: install epel-release (CentOS)
      yum:
        name: epel-release
        state: present
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install a list of packages with a list variable
      package:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"
      vars:
        packages:
        - htop
        - telnet
        - wget
        - curl
        - cockpit
        - net-tools
        - nload
        - openssh
        - openssh-server
        - openssh-clients
        - openssl-libs
        - chrony

    - name: Start cockpit service
      service:
        name: cockpit
        state: started

    - name: Start sshd service
      service:
        name: sshd
        state: started

    - name: Start chronyd service
      service:
        name: chronyd
        state: started