version: '3.4'

services:
  redis_with_password:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_with_password_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    configs:
      - source: redis.conf
        target: /usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1
      update_config:
        order: start-first
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '4'
          memory: 3000M
        reservations:
          cpus: '2'
          memory: 1500M
volumes:
  redis_with_password_data:
    external: true
configs:
  redis.conf:
    external: true
networks:
  infrastructure:
    external: true