---
- hosts: centos7.1
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes  
  tasks:
  # cai dat docker
    - name: update
      shell: |
        yum install -y epel-release 
        yum update -y
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: install python 3
      shell: |
        yum -y install python3
        yum -y install python3-pip git
        pip3 install --upgrade pip==21.3.1
   
    - name: install docker sdk for python
      shell: pip install docker

    - name: Cai dat docker swarm
      shell: |
         docker swarm init
    # Mo cac port can thiet
    - name: login dockerhub.dttt.vn
      shell: docker login dockerhub.dttt.vn -u="admin" -p="Trinam@2019"
        
    - name: Open port
      shell: |
        firewall-cmd --zone=public --add-port=2376/tcp --permanent					
        firewall-cmd --zone=public --add-port=2377/tcp --permanent					
        firewall-cmd --zone=public --add-port=4789/udp --permanent										
        firewall-cmd --zone=public --add-port=7946/tcp --add-port=22/tcp --add-port=9001/tcp --permanent
        firewall-cmd --zone=public --add-port=22/tcp --add-port=9001/tcp --permanent					
        firewall-cmd --reload
        systemctl restart docker

    # copy file stack infrastructure
    #- name: Copy file stack infrastructure
    #  copy: 
    #    src: /root/setup
    #    dest: /root/
    # dowload file stack
    - name: dowload file setup
      shell: |
        cd ~
        git clone https://github.com/dangkhoa0797/setup.git
        
    - name: pull image 1
      command: docker pull dockerhub.dttt.vn/documentserver:3.0
    - name: pull image 2
      shell: docker pull dockerhub.dttt.vn/etcdkeeper:latest
    - name: pull image 3
      shell: docker pull dockerhub.dttt.vn/imagemagick:latest
    
    # cai dat portainer

    - name: Cai dat Portaier
      shell: |
        docker stack deploy -c /root/setup/portainer.yml portainer

    - name: Cai dat traefik
      shell: |
        docker volume create ssl
        docker network create -d overlay traefik_main
        docker stack deploy -c /root/setup/traefik.yml traefik

    - name: Tao volume
      shell: |
        docker volume create mongo_data
        docker volume create rabbitmq_data
        docker volume create redis_data
        docker volume create rabbitmq_data
        docker volume create etcd_data
        docker volume create sqlserver_data
        
     # tao net work   
    - name: Tao network
      shell: |
        docker network create infrastructure -d overlay
    
    - name: config redis
      shell: |
        echo "user root on allkeys allchannels allcommands >VgJyAzye2YZIz3nT
        user default off" | docker config create redis.conf -

    - name: Cai dat infrastructure
      shell: |
        docker stack deploy -c /root/setup/infrastructure.yml infra
