---
- hosts: NAME
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  tasks:
  # cai dat docker
    - name: update
      shell: yum -y update
    - name: cai device-mapper-persistent-data lvm2
      shell: yum -y install yum-utils device-mapper-persistent-data lvm2
    - name: cai repo docker
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: cai docker
      shell: yum -y install docker-ce
    - name: cai docker-compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        ln -s /usr/local/bin/docker-compose /usr/bin/docker-compos
    - name: enabled docker
      shell: |
        systemctl start docker
        systemctl enable docker
        systemctl status docker
    - name: Cai dat docker swarm
      shell: docker swarm init
    # Mo cac port can thiet
    - name: login dockerhub.dttt.vn
      shell: docker login dockerhub.dttt.vn -u="admin" -p="Trinam@2019"
      register: ps

    - debug: var=ps.stdout_lines

    - name: cai dat git
      shell: yum -y install git
      tags: git
        
    - name: set up firewall
      shell: |
        firewall-cmd --zone=public --add-port=2376/tcp --permanent					
        firewall-cmd --zone=public --add-port=2377/tcp --permanent					
        firewall-cmd --zone=public --add-port=4789/udp --permanent										
        firewall-cmd --zone=public --add-port=7946/tcp --add-port=9001/tcp --permanent
        firewall-cmd --zone=public --add-port=2022/tcp --permanent					
        firewall-cmd --reload
        firewall-cmd --zone=public --list-ports
        systemctl restart docker
    #    yum -y install net-tools
    #    yum -y update
    #    sed -i "s,#Port 22,Port 2022," /etc/ssh/sshd_config
    #    firewall-cmd --zone=public --list-ports
    #    sed -i "s,SELINUX=.*,SELINUX=disabled," /etc/selinux/config
    #    setenforce 0
    #    systemctl restart sshd
        
    #  register: ps
    #
    #- debug: var=ps.stdout_lines
    
    # copy file stack infrastructure
    #- name: Copy file stack infrastructure
    #  copy: 
    #    src: /ansible/setup
    #    dest: /root/
    #  tags: cp
    - name: clone infra
      shell: git clone https://github.com/dangkhoa0797/setup.git
      tags: clone
        
    #- name: pull image 1
    #  command: docker pull dockerhub.dttt.vn/documentserver:3.0
    #  tags: im1
    - name: pull image 2
      shell: docker pull dockerhub.dttt.vn/etcdkeeper:latest
    - name: pull image 3
      shell: docker pull dockerhub.dttt.vn/imagemagick:latest
    
    # cai dat portainer

    - name: Cai dat Portaier
      shell: |
        docker stack deploy -c /root/setup/portainer.yml portainer
      tags: portainer

    - name: Cai dat traefik
      shell: |
        docker volume create ssl
        docker network create -d overlay traefik_main
        docker stack deploy -c /root/setup/traefik.yml traefik
      tags: traefik

    - name: Tao volume
      shell: |
        docker volume create mongo_data
        docker volume create rabbitmq_data
        docker volume create redis_data
        docker volume create rabbitmq_data
        docker volume create etcd_data
        docker volume create sqlserver_data
        
     # tao net work   
    - name: Tao network
      shell: |
        docker network create infrastructure -d overlay
    
    - name: config redis
      shell: |
        echo "user root on allkeys allchannels allcommands >VgJyAzye2YZIz3nT
        user default off" | docker config create redis.conf -

    - name: Cai dat infrastructure
      shell: |
        docker stack deploy -c /root/setup/infrastructure.yml infra
      tags: infra
