---
- hosts: NAME
  remote_user: root
  ignore_unreachable: yes
  ignore_errors: yes
  vars_files:
    - variables.yml
  tasks:
    - name: check port ssh
      shell: netstat -ltnp | grep ssh
      register: check 

    - debug: var=check.stdout_lines
    - name: set up firewall
      yum:
        name:
          - net-tools
    - name: Add port to firewalld
      firewalld:
        port: 2022/tcp
        permanent: yes
        state: enabled
    - name: change port default
      shell: sed -i "s,^#Port .*,Port 2022," /etc/ssh/sshd_config
    - name: change port default
      shell: sed -i "s,^Port .*,Port 2022," /etc/ssh/sshd_config
    - name: SELINUX=disabled
      shell: sed -i "s,SELINUX=.*,SELINUX=disabled," /etc/selinux/config
    - name: setenforce 0
      shell:  setenforce 0
    - name: restart sshd
      shell:  systemctl restart sshd
    - name: reload firewall
      shell: |					
        firewall-cmd --reload
        systemctl restart docker
    - name: check port ssh
      shell: netstat -ltnp | grep ssh
      register: check 

    - debug: var=check.stdout_lines